In [9]:
import numpy as np
import pandas as pd

In [17]:
df= pd.read_excel('102103562.xlsx')

In [107]:
a =np.arange(9)
len(a)

9

In [18]:
df = df.iloc[:,1:]
df

P1    P2   P3    P4     P5
0  0.84  0.71  6.7  42.1  12.59
1  0.91  0.83  7.0  31.7  10.11
2  0.79  0.62  4.8  46.7  13.23
3  0.78  0.61  6.4  42.4  12.55
4  0.94  0.88  3.6  62.2  16.91
5  0.88  0.77  6.5  51.5  14.91
6  0.66  0.44  5.3  48.9  13.83
7  0.93  0.86  3.4  37.0  10.55

In [69]:
mat = np.array([[250,16,12,5],[200,16,8,3],[300,32,16,4],[275,32,8,4],[255,16,16,2]])
mat

array([[250,  16,  12,   5],
       [200,  16,   8,   3],
       [300,  32,  16,   4],
       [275,  32,   8,   4],
       [255,  16,  16,   2]])

In [40]:
preprocessing.normalize(mat,'l1')

array([[0.88339223, 0.0565371 , 0.04240283, 0.01766784],
       [0.88105727, 0.07048458, 0.03524229, 0.01321586],
       [0.85227273, 0.09090909, 0.04545455, 0.01136364],
       [0.86206897, 0.10031348, 0.02507837, 0.01253918],
       [0.88235294, 0.05536332, 0.05536332, 0.00692042]])

In [103]:
rows,cols = mat.shape
wts= np.array([0.25]*4)
# mat / rootOfSumOfSquare * weight 
impact = [-1,1,1,1]
for i in range(cols):
    temp =0
    for j in range(rows):
        temp += mat[j,i]**2
    temp=temp**0.5
    wts[i] /=temp
    

weightedNormalized = mat*wts

idealBestWorst = []#(best,worst)

for i in range(cols):
    maxi = weightedNormalized[:,i].max()
    mini = weightedNormalized[:,i].min()
    idealBestWorst.append((maxi,mini) if impact[i] ==1 else (mini,maxi))

topsisScore = []
for i in range(rows):
    temp_p,temp_n = 0,0
    for j in range(cols):
        temp_p += (weightedNormalized[i][j] - idealBestWorst[j][0])**2
        temp_n += (weightedNormalized[i][j] - idealBestWorst[j][1])**2
    temp_p,temp_n = temp_p**0.5, temp_n**0.5
    topsisScore.append( temp_n / (temp_p+ temp_n))
df = pd.DataFrame(mat)
df["score"] = np.array(topsisScore).T

df['rank'] = df['score'].rank(method='max',ascending=False)
df['rank'] = df.astype({'rank':int})['rank']
    

In [104]:
df

0   1   2  3     score  rank
0  250  16  12  5  0.534362     3
1  200  16   8  3  0.305162     5
2  300  32  16  4  0.694838     1
3  275  32   8  4  0.535505     2
4  255  16  16  2  0.382517     4

In [19]:
arr = np.array(df)
print(arr)


[[ 0.84  0.71  6.7  42.1  12.59]
 [ 0.91  0.83  7.   31.7  10.11]
 [ 0.79  0.62  4.8  46.7  13.23]
 [ 0.78  0.61  6.4  42.4  12.55]
 [ 0.94  0.88  3.6  62.2  16.91]
 [ 0.88  0.77  6.5  51.5  14.91]
 [ 0.66  0.44  5.3  48.9  13.83]
 [ 0.93  0.86  3.4  37.   10.55]]


In [20]:
from sklearn import preprocessing

In [21]:
preprocessing.normalize(arr)

array([[0.01889183, 0.01596809, 0.15068482, 0.94684046, 0.28315253],
       [0.02674598, 0.02439469, 0.20573832, 0.9317007 , 0.29714492],
       [0.01619352, 0.01270884, 0.098391  , 0.95726242, 0.27119019],
       [0.01745354, 0.01364956, 0.14320852, 0.94875647, 0.28082297],
       [0.01455763, 0.01362842, 0.05575264, 0.96328165, 0.26188252],
       [0.01629022, 0.01425394, 0.1203255 , 0.95334816, 0.27600818],
       [0.01291588, 0.00861059, 0.10371844, 0.95694934, 0.27064641],
       [0.02406496, 0.02225362, 0.08797942, 0.95742312, 0.27299497]])

In [88]:
def topsis(df: pd.DataFrame, wts: np.ndarray, impact: np.ndarray) -> pd.DataFrame:
    mat = np.array(df.iloc[1:])
    rows, cols = mat.shape
    wts = np.array([0.25] * 4)
    # mat / rootOfSumOfSquare * weight
    impact = [-1, 1, 1, 1]
    for i in range(cols):
        temp = 0
        for j in range(rows):
            temp += mat[j, i] ** 2
        temp = temp**0.5
        wts[i] /= temp


    weightedNormalized = mat * wts

    idealBestWorst = []  # (best,worst)

    for i in range(cols):
        maxi = weightedNormalized[:, i].max()
        mini = weightedNormalized[:, i].min()
        idealBestWorst.append((maxi, mini) if impact[i] == 1 else (mini, maxi))

    topsisScore = []
    for i in range(rows):
        temp_p, temp_n = 0, 0
        for j in range(cols):
            temp_p += (weightedNormalized[i][j] - idealBestWorst[j][0]) ** 2
            temp_n += (weightedNormalized[i][j] - idealBestWorst[j][1]) ** 2
        temp_p, temp_n = temp_p**0.5, temp_n**0.5
        topsisScore.append(temp_n / (temp_p + temp_n))
    df = pd.DataFrame(mat)
    df["score"] = np.array(topsisScore).T 
    print("hello")

In [87]:
df

P1    P2   P3    P4     P5
0  0.84  0.71  6.7  42.1  12.59
1  0.91  0.83  7.0  31.7  10.11
2  0.79  0.62  4.8  46.7  13.23
3  0.78  0.61  6.4  42.4  12.55
4  0.94  0.88  3.6  62.2  16.91
5  0.88  0.77  6.5  51.5  14.91
6  0.66  0.44  5.3  48.9  13.83
7  0.93  0.86  3.4  37.0  10.55